[workspace]
members = [
    "crates/solum",
    "crates/processus",
    "crates/consolum",
    "crates/aleator",
    "crates/tempus",
    "crates/http",
    "crates/provider-contracts",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
faber = { package = "faber-runtime", path = "../faber-runtime" }
host-kernel = { path = "../host-kernel-rs" }
libc = "0.2"

[workspace.lints.clippy]
pedantic = "deny"
