[package]
name = "host-provider-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dev-dependencies]
aleator = { path = "../aleator" }
consolum = { path = "../consolum" }
host-kernel.workspace = true
processus = { path = "../processus" }
solum = { path = "../solum" }
tempus = { path = "../tempus" }
